package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jacobf00/solace/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, username string, email string, password string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// CreateProblem is the resolver for the createProblem field.
func (r *mutationResolver) CreateProblem(ctx context.Context, title string, description string, context *string, category *string) (*model.Problem, error) {
	panic(fmt.Errorf("not implemented: CreateProblem - createProblem"))
}

// UpdateProblemAdvice is the resolver for the updateProblemAdvice field.
func (r *mutationResolver) UpdateProblemAdvice(ctx context.Context, problemID uuid.UUID, advice string) (*model.Problem, error) {
	panic(fmt.Errorf("not implemented: UpdateProblemAdvice - updateProblemAdvice"))
}

// DeleteProblem is the resolver for the deleteProblem field.
func (r *mutationResolver) DeleteProblem(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteProblem - deleteProblem"))
}

// CreateReadingPlan is the resolver for the createReadingPlan field.
func (r *mutationResolver) CreateReadingPlan(ctx context.Context, problemID uuid.UUID, verseIds []uuid.UUID) (*model.ReadingPlan, error) {
	panic(fmt.Errorf("not implemented: CreateReadingPlan - createReadingPlan"))
}

// MarkVerseAsRead is the resolver for the markVerseAsRead field.
func (r *mutationResolver) MarkVerseAsRead(ctx context.Context, readingPlanID uuid.UUID, verseID uuid.UUID, isRead bool) (*model.ReadingPlanItem, error) {
	panic(fmt.Errorf("not implemented: MarkVerseAsRead - markVerseAsRead"))
}

// UpdateReadingProgress is the resolver for the updateReadingProgress field.
func (r *mutationResolver) UpdateReadingProgress(ctx context.Context, readingPlanID uuid.UUID, verseID uuid.UUID, isRead bool) (*model.ReadingPlanItem, error) {
	panic(fmt.Errorf("not implemented: UpdateReadingProgress - updateReadingProgress"))
}

// ReviseReadingPlan is the resolver for the reviseReadingPlan field.
func (r *mutationResolver) ReviseReadingPlan(ctx context.Context, planID uuid.UUID, changes model.PlanChanges) (*model.ReadingPlan, error) {
	panic(fmt.Errorf("not implemented: ReviseReadingPlan - reviseReadingPlan"))
}

// SubmitFeedback is the resolver for the submitFeedback field.
func (r *mutationResolver) SubmitFeedback(ctx context.Context, problemID uuid.UUID, rating int32, feedbackText *string) (*model.Feedback, error) {
	panic(fmt.Errorf("not implemented: SubmitFeedback - submitFeedback"))
}

// CreateFeedback is the resolver for the createFeedback field.
func (r *mutationResolver) CreateFeedback(ctx context.Context, problemID uuid.UUID, rating int32, feedbackText *string) (*model.Feedback, error) {
	panic(fmt.Errorf("not implemented: CreateFeedback - createFeedback"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Problem is the resolver for the problem field.
func (r *queryResolver) Problem(ctx context.Context, id uuid.UUID) (*model.Problem, error) {
	panic(fmt.Errorf("not implemented: Problem - problem"))
}

// ReadingPlan is the resolver for the readingPlan field.
func (r *queryResolver) ReadingPlan(ctx context.Context, id uuid.UUID) (*model.ReadingPlan, error) {
	panic(fmt.Errorf("not implemented: ReadingPlan - readingPlan"))
}

// Verse is the resolver for the verse field.
func (r *queryResolver) Verse(ctx context.Context, id uuid.UUID) (*model.Verse, error) {
	panic(fmt.Errorf("not implemented: Verse - verse"))
}

// VersesByBook is the resolver for the versesByBook field.
func (r *queryResolver) VersesByBook(ctx context.Context, book string, chapter *int32) ([]*model.Verse, error) {
	panic(fmt.Errorf("not implemented: VersesByBook - versesByBook"))
}

// AllBooks is the resolver for the allBooks field.
func (r *queryResolver) AllBooks(ctx context.Context) ([]string, error) {
	panic(fmt.Errorf("not implemented: AllBooks - allBooks"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// MyProblems is the resolver for the myProblems field.
func (r *queryResolver) MyProblems(ctx context.Context) ([]*model.Problem, error) {
	panic(fmt.Errorf("not implemented: MyProblems - myProblems"))
}

// SearchVerses is the resolver for the searchVerses field.
func (r *queryResolver) SearchVerses(ctx context.Context, query string, limit *int32) ([]*model.Verse, error) {
	panic(fmt.Errorf("not implemented: SearchVerses - searchVerses"))
}

// VersesByTopic is the resolver for the versesByTopic field.
func (r *queryResolver) VersesByTopic(ctx context.Context, topic string, limit *int32) ([]*model.Verse, error) {
	panic(fmt.Errorf("not implemented: VersesByTopic - versesByTopic"))
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
