// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Problem struct {
	ID          string       `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Context     *string      `json:"context,omitempty"`
	Category    *string      `json:"category,omitempty"`
	CreatedAt   time.Time    `json:"createdAt"`
	ReadingPlan *ReadingPlan `json:"readingPlan,omitempty"`
	Advice      *string      `json:"advice,omitempty"`
}

type Query struct {
}

type ReadingPlan struct {
	ID        string             `json:"id"`
	Problem   *Problem           `json:"problem"`
	CreatedAt time.Time          `json:"createdAt"`
	Items     []*ReadingPlanItem `json:"items"`
}

type ReadingPlanItem struct {
	ID        string `json:"id"`
	Verse     *Verse `json:"verse"`
	ItemOrder int32  `json:"itemOrder"`
	IsRead    bool   `json:"isRead"`
}

type User struct {
	ID       string     `json:"id"`
	Username string     `json:"username"`
	Email    string     `json:"email"`
	Problems []*Problem `json:"problems"`
}

type Verse struct {
	ID      string `json:"id"`
	Book    string `json:"book"`
	Chapter int32  `json:"chapter"`
	Verse   int32  `json:"verse"`
	Text    string `json:"text"`
}
