// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type AuthResponse struct {
	User  *User  `json:"user"`
	Token string `json:"token"`
}

type Feedback struct {
	ID           uuid.UUID  `json:"id"`
	ProblemID    uuid.UUID  `json:"problemId"`
	UserID       *uuid.UUID `json:"userId,omitempty"`
	Rating       int32      `json:"rating"`
	FeedbackText *string    `json:"feedbackText,omitempty"`
	IsHelpful    *bool      `json:"isHelpful,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    *time.Time `json:"updatedAt,omitempty"`
}

type FeedbackInput struct {
	ProblemID    uuid.UUID `json:"problemId"`
	Rating       int32     `json:"rating"`
	FeedbackText *string   `json:"feedbackText,omitempty"`
}

type Mutation struct {
}

type PlanChanges struct {
	AddedVerses     []uuid.UUID `json:"addedVerses,omitempty"`
	RemovedVerses   []uuid.UUID `json:"removedVerses,omitempty"`
	ReorderedVerses []uuid.UUID `json:"reorderedVerses,omitempty"`
	Notes           *string     `json:"notes,omitempty"`
}

type PlanRevision struct {
	ID             uuid.UUID  `json:"id"`
	ReadingPlanID  uuid.UUID  `json:"readingPlanId"`
	RevisionNumber int32      `json:"revisionNumber"`
	Changes        string     `json:"changes"`
	CreatedBy      *uuid.UUID `json:"createdBy,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type Problem struct {
	ID          uuid.UUID    `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Context     *string      `json:"context,omitempty"`
	Category    *string      `json:"category,omitempty"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   *time.Time   `json:"updatedAt,omitempty"`
	ReadingPlan *ReadingPlan `json:"readingPlan,omitempty"`
	Advice      *string      `json:"advice,omitempty"`
	UserID      uuid.UUID    `json:"userId"`
}

type Query struct {
}

type ReadingPlan struct {
	ID        uuid.UUID          `json:"id"`
	Problem   *Problem           `json:"problem"`
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt *time.Time         `json:"updatedAt,omitempty"`
	Items     []*ReadingPlanItem `json:"items"`
}

type ReadingPlanItem struct {
	ID        uuid.UUID  `json:"id"`
	Verse     *Verse     `json:"verse"`
	ItemOrder int32      `json:"itemOrder"`
	IsRead    bool       `json:"isRead"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type User struct {
	ID        uuid.UUID  `json:"id"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	Problems  []*Problem `json:"problems"`
	CreatedAt time.Time  `json:"createdAt"`
}

type Verse struct {
	ID      uuid.UUID `json:"id"`
	Book    string    `json:"book"`
	Chapter int32     `json:"chapter"`
	Verse   int32     `json:"verse"`
	Text    string    `json:"text"`
}

type VerseTopic struct {
	ID         uuid.UUID `json:"id"`
	VerseID    uuid.UUID `json:"verseId"`
	Topic      string    `json:"topic"`
	Confidence float64   `json:"confidence"`
	CreatedAt  time.Time `json:"createdAt"`
}
